/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andy_recustomviews_ndk_MyJni */

#ifndef _Included_com_andy_recustomviews_ndk_MyJni
#define _Included_com_andy_recustomviews_ndk_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andy_recustomviews_ndk_MyJni
 * Method:    displayJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andy_recustomviews_ndk_MyJni_displayJni
  (JNIEnv *, jobject);

/*
 * Class:     com_andy_recustomviews_ndk_MyJni
 * Method:    xyUpdate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andy_recustomviews_ndk_MyJni_xyUpdate
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_andy_recustomviews_ndk_MyJni
 * Method:    getIntArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_andy_recustomviews_ndk_MyJni_getIntArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_andy_recustomviews_ndk_MyJni
 * Method:    strConcat
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andy_recustomviews_ndk_MyJni_strConcat
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_andy_recustomviews_ndk_MyJni
 * Method:    newBean
 * Signature: (Ljava/lang/String;I)Lcom/andy/recustomviews/ndk/Bean;
 */
JNIEXPORT jobject JNICALL Java_com_andy_recustomviews_ndk_MyJni_newBean
  (JNIEnv *, jobject, jstring, jint)

#ifdef __cplusplus
}
#endif
#endif
